./batchrun.py bp/test/shear -r $1
./batchrun.py bp/test/extensional -r $1
./batchrun.py bp/test/drift -r $1
./batchrun.py bp/test/mix -r $1
./batchrun.py bp/test/poiseuille -r $1
./batchrun.py bp/test/2cap -r $1
./batchrun.py bp/test/collision5cap -r $1
./batchrun.py bp/test/3sph2ellip -r $1
./batchrun.py bp/test/spread -r $1
./batchrun.py bp/test/roll -r $1
./batchrun.py bp/test/rect-domain -r $1
